class PatternModel {
  final String id;
  final String name;
  final String type; // Bullish, Bearish, Neutral
  final String category; // Single, Double, Triple, Continuation
  final String description;
  final String signal;
  final String? imageUrl;

  PatternModel({
    required this.id,
    required this.name,
    required this.type,
    required this.category,
    required this.description,
    required this.signal,
    this.imageUrl,
  });
}

final mockPatterns = [
  PatternModel(
    id: '1',
    name: 'Doji',
    type: 'Neutral',
    category: 'Single',
    description: 'Forms when open and close prices are nearly equal. Represents extreme market indecision and a potential trend reversal.',
    signal: 'Neutral / Reversal Warning',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Candlestick_pattern_Doji_Star.jpg',
  ),
  PatternModel(
    id: '2',
    name: 'Bullish Hammer',
    type: 'Bullish',
    category: 'Single',
    description: 'A single candlestick pattern that forms at the bottom of a downtrend. It has a small real body at the top with a long lower shadow (at least 2x the body) and little to no upper shadow. The long lower wick shows that sellers pushed the price down significantly, but buyers stepped in and drove it back up near the open.',
    signal: 'Potential Bullish Reversal',
    imageUrl: 'Patterns/Bullish_Hammer.png',
  ),
  PatternModel(
    id: '3',
    name: 'Inverted Hammer',
    type: 'Bullish',
    category: 'Single',
    description: 'A single candlestick that appears at the bottom of a downtrend. It has a small real body at the bottom with a long upper shadow and little to no lower shadow. It shows that buyers attempted to push price higher during the session, though sellers pulled it back.',
    signal: 'Potential Bullish Reversal (Confirm with Next Candle)',
    imageUrl: 'Patterns/Inverted_Hammer.png',
  ),
  PatternModel(
    id: '4',
    name: 'Shooting Star',
    type: 'Bearish',
    category: 'Single',
    description: 'A single candlestick that forms at the top of an uptrend. It has a small real body near the bottom of the candle with a long upper shadow and little to no lower shadow. Buyers pushed the price up during the session, but sellers overwhelmed them and drove it back down.',
    signal: 'Potential Bearish Reversal',
    imageUrl: 'Patterns/Shooting_Star.png',
  ),
  PatternModel(
    id: '5',
    name: 'Hanging Man',
    type: 'Bearish',
    category: 'Single',
    description: 'A single candlestick that appears at the top of an uptrend. It looks identical to the Hammer but forms in an uptrend context - small real body at the top, long lower shadow, and little to no upper shadow. It warns that selling pressure is increasing beneath the surface.',
    signal: 'Potential Bearish Reversal (Confirm when Possible)',
    imageUrl: 'Patterns/Hanging_Man.png',
  ),
  PatternModel(
    id: '6',
    name: 'Bullish Marubozu',
    type: 'Bullish',
    category: 'Single',
    description: 'A single candlestick with a long green/white body and no (or very minimal) upper or lower shadows. The open is the low and the close is the high of the session. It represents complete buyer dominance throughout the entire period.',
    signal: 'Strong Bullish Continuation / Start of Uptrend',
    imageUrl: 'Patterns/Bullish_Marubozu.png',
  ),
  PatternModel(
    id: '21',
    name: 'Bearish Marubozu',
    type: 'Bearish',
    category: 'Single',
    description: 'A single candlestick with a long red/black body and no (or very minimal) upper or lower shadows. The open is the high and the close is the low of the session. It represents complete seller dominance throughout the entire period.',
    signal: 'Strong Bearish Continuation / Start of Downtrend',
    imageUrl: 'Patterns/Bearish_Marubozu.png',
  ),
  PatternModel(
    id: '7',
    name: 'Bullish Engulfing',
    type: 'Bullish',
    category: 'Double',
    description: 'A two-candlestick pattern that forms at the bottom of a downtrend. The first candle is a small bearish (red) candle, followed by a larger bullish (green) candle that completely engulfs the body of the first. It shows a strong shift in momentum from sellers to buyers.',
    signal: 'Reliable Bullish Reversal Signal',
    imageUrl: 'Patterns/Bullish_Engulfing.png',
  ),
  PatternModel(
    id: '8',
    name: 'Bearish Engulfing',
    type: 'Bearish',
    category: 'Double',
    description: 'A two-candlestick pattern that forms at the top of an uptrend. The first candle is a small bullish (green) candle, followed by a larger bearish (red) candle that completely engulfs the body of the first. It shows a strong shift in momentum from buyers to sellers.',
    signal: 'Reliable Bearish Reversal Signal',
    imageUrl: 'Patterns/Bearish_Engulfing.png',
  ),
  PatternModel(
    id: '9',
    name: 'Morning Doji Star',
    type: 'Bullish',
    category: 'Triple',
    description: 'A three-candlestick bullish reversal pattern that forms at the bottom of a downtrend. The first candle is a long bearish candle, the second is a Doji (open ≈ close) that gaps down, and the third is a long bullish candle that closes well into the first candle\'s body. The Doji reflects indecision before the bulls take control.',
    signal: 'Strong Bullish Reversal Signal',
    imageUrl: 'Patterns/Morning_Doji_Star.png',
  ),
  PatternModel(
    id: '10',
    name: 'Evening Doji Star',
    type: 'Bearish',
    category: 'Triple',
    description: 'A three-candlestick bearish reversal pattern that forms at the top of an uptrend. The first candle is a long bullish candle, the second is a Doji that gaps up, and the third is a long bearish candle that closes well into the first candle\'s body. The Doji signals indecision before the bears take control.',
    signal: 'Strong Bearish Reversal Signal',
    imageUrl: 'Patterns/Evening_Doji_Star.png',
  ),
  PatternModel(
    id: '11',
    name: 'Three White Soldiers',
    type: 'Bullish',
    category: 'Triple',
    description: 'A three-candlestick bullish pattern consisting of three consecutive long green/white candles, each opening within the previous candle\'s body and closing progressively higher. Each candle shows sustained buying pressure with small or no upper shadows. Appears after a downtrend or consolidation.',
    signal: 'Strong Bullish Reversal or Continuation',
    imageUrl: 'https://images.unsplash.com/photo-1611974715853-26dff9f98394?auto=format&fit=crop&q=80&w=400',
  ),
  PatternModel(
    id: '12',
    name: 'Three Black Crows',
    type: 'Bearish',
    category: 'Triple',
    description: 'A three-candlestick bearish pattern consisting of three consecutive long red/black candles, each opening within the previous candle\'s body and closing progressively lower. Each candle shows sustained selling pressure with small or no lower shadows. Appears after an uptrend or consolidation.',
    signal: 'Strong Bearish Reversal or Continuation',
    imageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&q=80&w=400',
  ),
  PatternModel(
    id: '13',
    name: 'Tweezer Bottom',
    type: 'Bullish',
    category: 'Double',
    description: 'A two-candlestick bullish reversal pattern that forms at the bottom of a downtrend. Two consecutive candles have matching or nearly identical lows — the first is bearish and the second is bullish. The equal lows indicate strong support at that level and a potential shift from sellers to buyers.',
    signal: 'Bullish Reversal (Confirmed by Next Move)',
    imageUrl: 'Patterns/Tweezer_Bottom.png',
  ),
  PatternModel(
    id: '14',
    name: 'Tweezer Top',
    type: 'Bearish',
    category: 'Double',
    description: 'A two-candlestick bearish reversal pattern that forms at the top of an uptrend. Two consecutive candles have matching or nearly identical highs — the first is bullish and the second is bearish. The equal highs indicate strong resistance at that level and a potential shift from buyers to sellers.',
    signal: 'Bearish Reversal (Confirmed by Next Move)',
    imageUrl: 'Patterns/Tweezer_Top.png',
  ),
  PatternModel(
    id: '22',
    name: 'Bullish Pin Bar',
    type: 'Bullish',
    category: 'Single',
    description: 'A single candlestick with a very long lower wick (shadow), a small body near the top of the candle, and little to no upper wick. It shows that price was aggressively rejected at lower levels, with buyers driving it back up to close near the high. Often forms at key support levels or trendlines.',
    signal: 'Potential Bullish Reversal',
    imageUrl: 'Patterns/Bullish_Pin_Bar.png',
  ),
  PatternModel(
    id: '23',
    name: 'Bearish Pin Bar',
    type: 'Bearish',
    category: 'Single',
    description: 'A single candlestick with a very long upper wick (shadow), a small body near the bottom of the candle, and little to no lower wick. It shows that price was aggressively rejected at higher levels, with sellers driving it back down to close near the low. Often forms at key resistance levels or trendlines.',
    signal: 'Potential Bearish Reversal',
    imageUrl: 'Patterns/Bearish_Pin_Bar.png',
  ),
  PatternModel(
    id: '24',
    name: 'Bullish Inside Bar',
    type: 'Bullish',
    category: 'Double',
    description: 'A two-candlestick pattern where the second candle\'s high and low are completely within the range of the first (mother) candle. In a bullish context, it forms after a downtrend or at a support level and represents a period of consolidation before a potential breakout to the upside.',
    signal: 'Bullish Breakout Potential (Look for High Break)',
    imageUrl: 'Patterns/Bullish_Inside_Bar.png',
  ),
  PatternModel(
    id: '25',
    name: 'Bearish Inside Bar',
    type: 'Bearish',
    category: 'Double',
    description: 'A two-candlestick pattern where the second candle\'s high and low are completely within the range of the first (mother) candle. In a bearish context, it forms after an uptrend or at a resistance level and represents a period of consolidation before a potential breakout to the downside.',
    signal: 'Bearish Breakout Potential (Look for Low Break)',
    imageUrl: 'Patterns/Bearish_Inside_Bar.png',
  ),
  PatternModel(
    id: '20',
    name: 'Dragonfly Doji',
    type: 'Bullish',
    category: 'Single',
    description: 'A single candlestick where the open, high, and close are all at or near the same level, producing a very long lower shadow and no upper shadow. It shows that sellers drove price down aggressively during the session, but buyers fully recovered all losses by the close.',
    signal: 'Strong Bullish Reversal (Bottom of Downtrend)',
    imageUrl: 'Patterns/Dragonfly_Dogi.png',
  ),
];
